### ISSUE TITLE
Many models have same names meshes with different textures

### ISSUE THREAD

**Issue by likeproblem** [PorktoberRevolution/ReStocked#1027]
For example Shielded Docking Port has two meshes, DockingPortShldBase, but the use different textures, why would you ask that's a problem? Im making recoloring with Textures Unlimited, and I can only filter out using mesh names, so both of these meshes get overriten and look horrible. So please name meshes unique in models, it's a pain to develop TU mod for them

**Comment by Poodmund** [comment]
Sorry, but the chance of this happening is extremely slim to none.

**Comment by likeproblem** [comment]
@Poodmund we are developing mod as usual, and wanted to know one thing. I have successfully changed bunch of models just to rename meshes, and since it is easy and we are going to go over ALL the parts anyway, could we pull request all changed models when done?

**Comment by ChrisAdderley** [comment]
Generally speaking
- Contributors my or may not change models in response to this kind of request. Contributors have expressed no interest in doing this
- Please respect the license of the models (as per the readme, license documentations and contributor lists) and do not redistribute them.

**Comment by likeproblem** [comment]
> Generally speaking
> 
> * Contributors may or may not change models in response to this kind of request. Contributors have expressed no interest in doing this.
> * Please respect the license of the models (as per the readme, license documentations and contributor lists) and do not redistribute them in original or modified form.

So I see we can't modify models at restock side nor at our side? That's sad

**Comment by likeproblem** [comment]
@ChrisAdderley , I have read the license and cfgs, seems you are the creator of both renamed models as of right now, and it states "Full rights license" or something like that, so could we ask for permission to distribute modified models, please?

**Comment by Spartwo** [comment]
To add much needed context, we would do the work to adjust the config files and models, making a formalised pull request with all the renamed transforms once TURD for Restock is out.

**Comment by Poodmund** [comment]
I think to nip this conversation in the bud now, you have made the formal request to modify and redistribute this mod's assets (models & textures) and that request has been politely denied. 

The contributors to this mod have expressed no interest, publicly or privately, in changing the assets, and also are not interested in receiving pull requests to amend the existing assets to ones from your project. This is due to a few reasons, but a primary one being that .mu files that are imported in Blender, and then exported again, go through a metaphorical wrangler upon import and also have a load of additional bloat added to the file on export (compare the file sizes of the original asset and your modified version). The team have no interest in performing the regression testing that is required to meet the our standards.

Please be respectful of the contributors and the asset licenses. Our apologies, but we have no interest in supporting this.

**Comment by Spartwo** [comment]
![image](https://github.com/user-attachments/assets/0af96af4-749b-40dc-8bdd-bc73e11c6d8f)

The modified one is smaller, I made optomisations by eliminating duplicate meshes and adjusting the variants
