### ISSUE TITLE
Cheetah engine has its thrust offset. 

### ISSUE THREAD

**Issue by dok377** [PorktoberRevolution/ReStocked#1032]
**Describe the bug**
A very easy way to see this would be to install RCS Build Aid Kit and enable it, then just node attach the engine to a fuel tank. The outer nozzles thrust is offset and it's inducing roll. 

**Screenshots**
![2024-11-09_235555](https://github.com/user-attachments/assets/d23b5a7f-8a85-4e08-9a1b-f5761d39ad5b)

**List of mods installed:**
 - Restock
 - RCS Build Aid Kit

**Logs**
Not relevant.

**Comment by Poodmund** [comment]
Thank you for the report, I can confirm this.

No roll from the vernier thrusters:
![image](https://github.com/user-attachments/assets/fb009231-9a7f-4a75-aac0-360f96d46954)

Full anti-clockwise roll from the vernier thrusters:
![image](https://github.com/user-attachments/assets/20115612-e732-45f3-b90f-a87f24134b76)

Full clockwise roll from the vernier thrusters:
![image](https://github.com/user-attachments/assets/7d8e96ec-3451-4645-ba51-31e6f903ef26)

Note the thrust torque is non-zero in default state and the varying levels of thrust torque at max roll gimballing.

**Comment by Poodmund** [comment]
In the asset, the parent vernier_gimbal nodes should have their location and rotation values 'zeroed' out (remove trailing insignificant figures) for all nodes:
![image](https://github.com/user-attachments/assets/d1be4e7b-e6b1-40b6-9114-3a456f7c6c8c)

 And the thrustTransform nodes should have their Z location values set to 0 for all nodes:
 ![image](https://github.com/user-attachments/assets/cd41dbe8-e8eb-40a6-bd35-35cbe2a2fe3a)

Due to a slight offset in the vernier nozzle meshes around the centre axis, the thrust transforms will be ever so slightly offset visually from the model (but to a very minor extent, not noticeable) and the fx transforms can stay as is so that the plumes are still aligned with the mesh.

This offset can be seen below in the current model's thrust transform locations from the top view:
 ![image](https://github.com/user-attachments/assets/bbdda6d2-58d1-4c86-88cb-e40d767afb36)
 
 And this is the same view with the thrust transforms, Z position values set to 0:
![image](https://github.com/user-attachments/assets/cdb20551-2903-43ca-9d89-69dd9f314e40)

**Comment by dok377** [comment]
Good info about the patch, I might disable it for the time being while waiting for the fix. Also another thing about the model, these vernier engines are a little too big, I think. They barely fit in the shroud of the engine, even. Probably not that important, since it would require a whole design change, but I just wanted to mention that.

**Comment by Poodmund** [comment]
@dok377 do you want to try the updated .mu here: https://github.com/PorktoberRevolution/ReStocked/commit/17c75dc6c61c010df9e2ecd41a6e986e1008588c

**Comment by dok377** [comment]
@Poodmund 
Can confirm, now RCS Build Aid shows no roll in the editor. Fired the engine without SAS and it doesn't rotate anymore, Great work.
