### ISSUE TITLE
poodle - all actuators in both versions need to rotated 90 degrees in their vertical axis

### ISSUE THREAD

**Issue by riocrokite** [PorktoberRevolution/ReStocked#133]
![image](https://user-images.githubusercontent.com/9766897/51064567-aecd1e00-1600-11e9-853a-b223d0b01735.png)

bottom and upper parts of all four actuators need to be rotated (for both engine versions)

**Comment by ChrisAdderley** [comment]
Fixed in b647efb

**Comment by Poodmund** [comment]
The actuator rings around the frame near to the throats are resolved with https://github.com/PorktoberRevolution/ReStocked/commit/b647efb14fbe6755c0ceac5d0960f35acdb8f809 but I think the connectors are the engine frame end are still 90 degrees out of alignment. See screenshots below:

![untitled-1](https://user-images.githubusercontent.com/10106634/51075325-d617ff80-1681-11e9-96e0-21856a03c20a.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/51075327-d912f000-1681-11e9-9283-165aff104825.png)

It looks as though the fat side of the connector is entering the pivot joint rather than aligning parallel with the thin sides (sorry for the terrible description).

Also, on the actuator connection rings near the engine throats, when gimballing it seems as if these rotate around the frame when the engine gimballs horizontally against each connection. See screenshots below showing no gimbal and then full gimbal (in horizontal direction. Oppositely opposed connections will experience this).

![untitled-3](https://user-images.githubusercontent.com/10106634/51075355-2abb7a80-1682-11e9-821f-d2c98bf25e96.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/51075356-2ee79800-1682-11e9-98dd-e2f4097092f8.png)

It seems as if they rotate around the frame and clip slightly through the frame mesh rather than slide along the frame (this is being very pernickety). If this is intended or too minor detail then please disregard.

**Comment by ChrisAdderley** [comment]
Ah for some reason I didn't notice the top parts. 

The second thing you mention is a limitation of KSP's lookconstraints, they are not axially constrained so will tilt a bit.

**Comment by Poodmund** [comment]
Yeah I thought as much. Like I said in my previous message, its a rather trivial detail in the grand scheme of the gimballing mechanism. I'd just like to point out that this whole gimbal looks awesome in action... good job guys!

**Comment by drewcassidy** [comment]
I think the misalignment is actually more realistic, I imaging in a real design you would use a ball joint there for the linkage 
![ball linkage](https://images1.mcmaster.com/mvB/contents/gfx/large/60645k161p1-d03c-digitall.png?ver=1479369924)

**Comment by ChrisAdderley** [comment]
Should actually be fixed in 32e48a9

**Comment by Poodmund** [comment]
Resolved as of https://github.com/PorktoberRevolution/ReStocked/commit/32e48a90d5377a4f9b0fa1e146d580a69a568024

![untitled-1](https://user-images.githubusercontent.com/10106634/51084991-cef8fc00-172a-11e9-92e3-7a78efef2ae6.png)
