### ISSUE TITLE
Clean up PartVariant colour tags

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#233]
The little tags for variants in the UI need a pass for consistency between parts. Currently they are not consistent and all over the place - a standardized scheme should be developed. 

@Poodmund this is likely a candidate for looking at in your QA pass.

**Comment by Poodmund** [comment]
I'll go through all the parts I guess. 😣🔫

**Comment by ChrisAdderley** [comment]
Oh I did this a few hours ago actually. Feel free to check it but it should be consistent now. 
Boattails are white/manufacturer
Basic is grey/manufacturer
Compact is grey

**Comment by Poodmund** [comment]
Oh, I didn't realise that you were talking about the actual descriptor strings. I was thinking more the order of the variants i.e. 1.25m, Boat Tail, Compact rather than Boat Tail, Compact, 1.25m, and making sure that the correct variant is selected by default.

I'll have to compare all parts to the relevant parts in stock and copy a similar layout.

**Comment by ChrisAdderley** [comment]
Nah I just means the colours of the icons in the switcher menu for the different variants. I will put this in verification if you could confirm they are consistent when you have time.

**Comment by Poodmund** [comment]
Moved to 'To Do' in 0.1.0 Project. When almost all 0.1.0 parts are in Master, I will run through them all and ensure the default variant selected is correct and order of variants listed is correct as per stock.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/76fbe3a4d3cc045a6a2f7cb1e9ac84169fdb14a4
