### ISSUE TITLE
Missing key for preventing Ven Stock Revamp override

### ISSUE THREAD

**Issue by T10a** [PorktoberRevolution/ReStocked#30]
In recent builds of Ven Stock Revamp, there was a key added called `VSRexclude = <boolean>` which, in the Path Patches config lets that override ignore parts with that key. Implementing it can allow VSR and ReStocked to coexist without weird "merged" models.

**Comment by 51ngular1ty** [comment]
I don't think that key would prevent the merged model issue.  That key if, I am not mistaken, is if you are making a new part that references the stock models.

**Comment by blowfishpro** [comment]
The mod in question knows how to deal with the stock models, it's a question of making sure VSR doesn't also try to modify them

**Comment by TykoTek** [comment]
I'm speaking with Kerbas_ad_astra about this. They gave me the instructions below thought it should work.

"Yes, define the variable "VSRexclude = true" (or "True", or "supercalifrue", or anything that ends with the letters "rue") in the config and none of the VSR patches will touch it."

They're looking into why it's not working but said it might be a while due to other projects. If I hear anything back I'll share it here.

**Comment by ChrisAdderley** [comment]
I'm also not completely sure about what method we will use to handle the compatibility between the two mods yet so I'm going to hold off on implementing any of this.
