### ISSUE TITLE
Pricing for the Mallet SRB is too expensive

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#314]
The Mallet SRB is the same price as the more capable Striker and Flea. It should be a bit more than half the price, given that it has half the propellant, and the "cheap launch vehicle" reference in the description.

**Comment by TykoTek** [comment]
The fuel is a fixed cost at .6 kerbucks per unit. If you remove the fuel from all 4 cheap boosters you get the following "dry" cost

Hammer = 175
Flea = 116
Striker = 104
Mallet = 152

A Mallet dry cost of somewhere a bit below 100 would make sense since the working hardware is nearly identical to Striker and it's just the cost of the extra tankage.

**Comment by ChrisAdderley** [comment]
I am always receptive to numbers that I can put into configs

**Comment by TykoTek** [comment]
Since the config "cost" includes fuel total cost. Hammer is 400, Flea & Striker are 200. Just for reference a Sepratron is 75, so I think 100 would be bit low. (not that stock costs are carefully balanced LOL)

Maybe 125? How does that sound @GregroxMun ?

**Comment by GregroxMun** [comment]
125 wet cost sounds right.

**Comment by ChrisAdderley** [comment]
Changed to 125 in 763a495
