### ISSUE TITLE
Heat Shield (0.625) - Shroud missing

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#346]
The shroud is missing when another part is snapped below it

![image](https://user-images.githubusercontent.com/22890228/52526249-9e917880-2c6a-11e9-9e04-554c56b400a9.png)

**Comment by ChrisAdderley** [comment]
Might be helped by 8c5f04c? I don't see a problem myself though - note that there are two nodes to attach to.

**Comment by TykoTek** [comment]
I can see both nodes now. They're really close together which makes it a bit fidgety to use. 

Could you lower the shrouded node a bit? Adding a little height to the shroud shouldn't break anything and it would make the part easier to use.

**Comment by woeller** [comment]
It's almost impossible to use the shroud node. I always had to attach a part to the heat shield node to use the shroud node and then remove the part from the heat shield.

**Comment by Poodmund** [comment]
Here's a video showing the finickiness of the nodes getting the shroud to appear: https://www.youtube.com/watch?v=VUSgYcbb6kE

It seems the easiest way is to first attach something to the node that doesn't trigger the shroud and then attach the part onto the remaining 'shroud node'. Then remove the helper part.

This is a similar issue to the one that Ven's Engines used to suffer with getting the boat tails to appear/disappear because the nodes were close and 'sticky'. You get that part 'bounce' when trying to place the part as it hops between the two available nodes.

Not sure what to suggest... is it possible to have, say, like phantom placed nodes where the node is shown as further away but when you attach to that node, it jumps back to its correct position?

**Comment by TykoTek** [comment]
Can you set which node is primary? It really seems to gravitate to the "no shroud" node whether I come at it from above or below.

**Comment by ChrisAdderley** [comment]
Moved things around and it now seems easy to hit either node as required in 458e07d

**Comment by TykoTek** [comment]
Awesome!!
