### ISSUE TITLE
Deployable solar panels  get set to a different angle when loading vanilla saves with ReStocked

### ISSUE THREAD

**Issue by JayJohnnson** [PorktoberRevolution/ReStocked#506]
Screenshots say it all really: 
![1](https://user-images.githubusercontent.com/48293868/53903137-381e3100-4043-11e9-8ae9-4af353b69645.jpg)
![2](https://user-images.githubusercontent.com/48293868/53903151-3eaca880-4043-11e9-854a-32fc415d66b4.jpg)
The real problem is unretractable panels and retractable panels that stick into the ground because of the issue, sending my base flying and breaking lots of panels:
![20190306192037_1](https://user-images.githubusercontent.com/48293868/53903910-29d11480-4045-11e9-88f1-d1a4963c7081.jpg)

**Comment by drewcassidy** [comment]
Pivot transforms on the panels are in the wrong orientation so when the game loads deployed panels from a save they end up pointing the wrong way. 
Unfortunately the same issue will happen after the fix when any vessel saved with the current version of restock is loaded, since the pivot will be rotated back to where it is in stock. I’ll write a small MM patch to make the bare solar panels retractable temporarily to help with fixing this

**Comment by JayJohnnson** [comment]
And with the panels sticking into the ground I'd have to edit the save or uninstall, retract if possible and reinstall?

**Comment by drewcassidy** [comment]
if you leave them as-is they will be the correct orientation when you load the version after the fix. any parts you either deployed while restock was installed, or did the retract-deploy move to, will need to be re-deployed or save-edited unfortunately

**Comment by drewcassidy** [comment]
Should be fixed with commit f6f881f7dd44a94ec723465738128eb151a2d309 if you want to test before the patch goes live.
