### ISSUE TITLE
RealChute Compatability

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#530]
Something is problematic when RealChute is installed. 

Should be fixed on our end likely

**Comment by ChrisAdderley** [comment]
The specific issue is that RealChute modifies the stock chute config with model items. Not a difficult fix: 
https://github.com/StupidChris/RealChute/blob/v1.4.7.3/Output/GameData/RealChute/ModuleManager/Stock_RealChute_MM.cfg#L35

**Comment by ChrisAdderley** [comment]
Added MM patch to fix in a229b0a

**Comment by ChrisAdderley** [comment]
Confirmed not fixed. https://forum.kerbalspaceprogram.com/index.php?/topic/182679-161-restock-revamping-ksps-art/&page=8&tab=comments#comment-3554499

**Comment by Carnildo** [comment]
My testing says it's a partial fix: it gets rid of the NullReferenceExceptions in the VAB,  but not the excessive drag on launch.

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/54072767-62583480-4277-11e9-8523-d439a514250a.png)

With the latest commit as of this time, as above, there is a huge amount of drag being caused by the chutes even at minimal speeds.

The above is on a vanilla 1.6.1 install with only ReStock, RS+, RealChute and with the PartDatabase being force rebuilt.

**Comment by ChrisAdderley** [comment]
Tentatively fixed with the last push. Removed the custom drag cubes in the presence of RealChute.

**Comment by Carnildo** [comment]
A quick test says it's fixed.

**Comment by ChrisAdderley** [comment]
Great!
