### ISSUE TITLE
RealPlume Compatibility

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#533]
This is mostly because we restuctured how models are built. This should probably be fixed on our end...

**Comment by ChrisAdderley** [comment]
This will be included in a future RealPlume update actually, but I will keep this open in verification until it is released

**Comment by blowfishpro** [comment]
I'm tempted to say it would be nice if some of your very good ReStock effects were upstreamed into RealPlume

**Comment by Vladimir-csp** [comment]
https://github.com/KSP-RO/RealPlume-StockConfigs/pull/81

But there are problems with: Vector, RAPIER, Hammer, Flea.
Hammer and Flea use stock plume. This seems to be either RealPlume's problem or some new Squad's thing.
For Vector I was unable to position plume components properly. If using thrustTransform, positions of main flare and shock cone are stretched many meters apart. If using fxTransformPlume, shock cone is shifted to the side:
```
@PART[SSME]:FOR[RealPlume]:NEEDS[SmokeScreen] // S3 KS-25 "Vector" Liquid Fuel Engine
{
    PLUME
    {
        name = Hydrolox-Lower
        transformName:NEEDS[!ReStock] = thrustTransform
        localRotation:NEEDS[!ReStock] = 0,0,0
        plumePosition:NEEDS[!ReStock] = 0,0,1.2
        flarePosition:NEEDS[!ReStock] = 0,0,0.5
        transformName:NEEDS[ReStock] = fxTransformPlume
        localRotation:NEEDS[ReStock] = 90,0,0
        plumePosition:NEEDS[ReStock] = 0,-1,0.0
        flarePosition:NEEDS[ReStock] = 0,-0.3,0.3
        plumeScale = 1.5
        flareScale:NEEDS[!ReStock] = 1.9
        flareScale:NEEDS[ReStock] = 1.5
        energy = 1
        speed = 0.8
        emissionMult = 1
    }
    @MODULE[ModuleEngines*]
    {
        %powerEffectName =  Hydrolox-Lower
    }
}
```
Funny thing, Mammoth works perfectly with the original config, I did not touch it.

With RAPIER it's the same thing. I was able to position rocket variant more or less correctly with fxTransformPlume, but plumes have different heights for each nozzle.
Turbojet variant is all over the place.
```
@PART[RAPIER]:FOR[RealPlume]:NEEDS[SmokeScreen] // CR-7 R.A.P.I.E.R. Engine
{
    PLUME
    {
        name = Turbojet
        transformName:NEEDS[!ReStock] = thrustTransform
        localRotation:NEEDS[!ReStock] = 0,0,0
        localPosition:NEEDS[!ReStock] = 0,0,-0.3
	transformName:NEEDS[ReStock] = fxTransformPlume
        localRotation:NEEDS[ReStock] = 90,0,0
        localPosition:NEEDS[ReStock] = 0,0.27,0
        fixedScale = 0.7
        energy = 0.8
        speed = 1
        emissionMult = 1.0
    }
    PLUME
    {
        name = Hypergolic-Lower
        transformName:NEEDS[!ReStock] = thrustTransform
        localRotation:NEEDS[!ReStock] = 0,0,0
        plumePosition:NEEDS[!ReStock] = 0,0,0.2
        flarePosition:NEEDS[!ReStock] = 0,0,0.4
	transformName:NEEDS[ReStock] = fxTransformPlume
        localRotation:NEEDS[ReStock] = 90,0,0
        plumePosition:NEEDS[ReStock] = 0,-0.15,0
        flarePosition:NEEDS[ReStock] = 0,-0.25,0
        plumeScale = 0.4
        flareScale = 0.6
        energy = 1
        speed = 1
        emissionMult = 1.0
    }
    @MODULE[ModuleEngines*],0
    {
        %powerEffectName = Turbojet
        %spoolEffectName = Turbojet-Spool
    }
    @MODULE[ModuleEngines*],1
    {
        %powerEffectName = Hypergolic-Lower
    }
}
```
For every engine that I had to use fxTransformPlume, coordinates are weird and unintuitive due to 90 degree rotation.

**Comment by ChrisAdderley** [comment]
I'll check the scale of the thrustTransform objects on the RAPIER, Flea and Hammer and found them all correct. 
However, I will point out that they are very *not* correct in stock. 
The Vector does seem to have bad scaling in Restock and I will check this out.

**Comment by ChrisAdderley** [comment]
Vector TT scaling was fixed in the latest release.

**Comment by Vladimir-csp** [comment]
Vector support is finished!
Now to the RAPIER:
![plumes](https://user-images.githubusercontent.com/4061903/54224200-17098480-450a-11e9-86d4-026019c8917f.png)
Here is the turbojet variant using fxTransformPlume. Two problems:
- Plume components are severely misaligned laterally despite one set of coordinates applies to both of them.
- Plume originates at slightly different height for each nozzle.

If applying to thrustTransform, only one nozzle gets the plume.

**Comment by ChrisAdderley** [comment]
Definitely not seeing that problem in the positions of the transforms:

![ttpersp](https://user-images.githubusercontent.com/5642064/54225768-a470b880-44b9-11e9-892f-aaa3fa274e74.PNG)
![ttside](https://user-images.githubusercontent.com/5642064/54225769-a470b880-44b9-11e9-8f3c-9cd9a7c2ff22.PNG)
![ttbot](https://user-images.githubusercontent.com/5642064/54225770-a470b880-44b9-11e9-9b1d-6c93e9cce5c6.PNG)

**Comment by lmtz2000** [comment]
I am having trouble with the Mailsail, Reliant and Skipper engines having their plume too far away straight under the engine bell. Any ideas on a fix? All other engines work fine as far as I can tell.

**Comment by TykoTek** [comment]
Here's a full rundown on all the LFO engines: 

Reliant = Plume starts too far from engine bell
Mainsail = Plume starts too far from engine bell
Skipper = Plume starts too far from engine bell
Poodle = only getting two plumes instead of 4
Terrier = Plume too deep in engine bell - it's spreading out through the sides of the bell
Rhino = Plume too deep in engine bell - it's spreading out through the sides of the bell
Torch = Need RP config - it's using ReStock plume
Boar = Need RP config - it's using ReStock plume
Corgi = Need RP config - it's using ReStock plume
Twin-Boar = Plumes too widely spaced - need to be re-centered over engine bells

**Comment by Vladimir-csp** [comment]
Fixes already pending: https://github.com/KSP-RO/RealPlume-StockConfigs/pull/81

**Comment by zorg2044** [comment]
Just a heads up, the following PR has just been merged into the dev branch which basically adds native realplume support on restock's side.

[https://github.com/PorktoberRevolution/ReStocked/pull/649](url)

Its been set up in such a way that it works together with realplume stock configs. RP-stock will configure everything and ReStock will overwrite with its own custom stuff and in some instances make corrections to the RP-stock ones. This way restock is unaffected by the lack of updates to RP-stock.

With a few exceptions such as SRBS, restock models will get custom realplumes that use either native ReStock fx, CryoEngines FX, or PlumeParty FX (upstreamed into ReStock with permission from Jade of Maar) to build the expanding plumes.

Please let me know if anyone sees any issues. Its still in testing phase.

**Comment by zorg2044** [comment]
The above PR has been reverted and official RealPlume support is now available via

RealPlume-Stock v1.4.0

https://github.com/KSP-RO/RealPlume-StockConfigs/releases

Requires RealPlume v12.0.0 which is bundled with RP-stock
