### ISSUE TITLE
Feature Request - add an attachment node to bottom center of Mammoth

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#56]
The Mammoth is just begging for an option to attach a Vector in the center to make a 5 engine cluster. It even looks like you designed the shape to accommodate one, but there's no node there.

**Comment by Poodmund** [comment]
Ah! There is already an issue about this... see how neat it'd be:

![untitled-1](https://user-images.githubusercontent.com/10106634/52523032-b7a72300-2c84-11e9-895c-02f291991426.png)

**Comment by ChrisAdderley** [comment]
Added in f950fea

**Comment by Poodmund** [comment]
May I suggest a different position for the new node?

The once in the https://github.com/PorktoberRevolution/ReStocked/commit/f950feaabac4da21a1121b605846d191de46598e commit is aligned to the height of the outer-most rim as seen in the screenshots below which causes the attached part to float between the bottom of the engine and where the node sits:

![untitled-1](https://user-images.githubusercontent.com/10106634/52540374-b4915d00-2d80-11e9-9d14-3e1616944bdf.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52540378-b78c4d80-2d80-11e9-8bb5-5008ca78f0d9.png)

I opened up the mesh in Blender and snaped an empty to the center of that bottom face and it gives a position of -1.20352 so I set the node to that position using:

```
// Adds a bottom node to the mammoth

@PART[Size3EngineCluster]
{
  node_stack_bottom = 0.0, -1.20352, 0.0, 0.0, -1.0, 0.0, 1
}
```
It now sits the node directly on the model surface:

![untitled-3](https://user-images.githubusercontent.com/10106634/52540397-e99daf80-2d80-11e9-8cf3-03f90978a892.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/52540401-ed313680-2d80-11e9-9b26-6bac51e8b716.png)

Its pretty dead on the surface of the model:

![untitled-5](https://user-images.githubusercontent.com/10106634/52540405-f3bfae00-2d80-11e9-9797-6d9a46442082.png)

It lets you attach 1.25m parts directly flush with the engine base rather than sitting off the model:

![untitled-6](https://user-images.githubusercontent.com/10106634/52540416-13ef6d00-2d81-11e9-9ad3-55878ff6a5e6.png)

Do you have any thoughts on this? Are there any issues with having the node situated within the collider mesh like this assuming that any engines attached to the node would have to have their thrust transform outside of the collider?

![untitled-7](https://user-images.githubusercontent.com/10106634/52540455-79435e00-2d81-11e9-88d4-665b69590db9.png)

**Comment by TykoTek** [comment]
The Vector works either way since the part sits pretty deep in the parent it's attached. Since adding a Vector is the most common use case, it would work either way.

If possible to lower it as @Poodmund suggests that would be better for attaching other parts though.

**Comment by ChrisAdderley** [comment]
Well it's you guys' request :P could have just said I put it in the wrong place :P.

Moved in latest push

**Comment by TykoTek** [comment]
Nice! thanks! I'm still loving the use-case of adding a Pug to the center.  "gosh, if I only had 4025kN instead of 4000 this rocket would be perfect"
