### ISSUE TITLE
Bring back the yellow (and other colorful aspects)

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#609]
This is a fairly subjective suggestion and probably not a priority, but I thought I'd make it anyway.

I *really* miss the yellow on monopropellant tanks. That splash of color (or in the old 2.5m tank, color and a different shade of gray) really looks great on those old ships. There's something about that aesthetic from 0.18 to 1.3's rocket parts, that Porkjet's revamps and ReStock don't *quite* capture, that is very pleasing, and I think a big part of it is the varied color, rather than almost everything being white and gray, and the only other color really being orange. There was something very nice about the black and yellow striping of some parts in my opinion. (The spaceplane monoprop parts also still use yellow)

![An old 0.18 style FL-R25 RCS tank](https://wiki.kerbalspaceprogram.com/images/thumb/d/dd/FL-R25_FT.png/190px-FL-R25_FT.png)
![A current Mk3 Monopropellant Tank](https://wiki.kerbalspaceprogram.com/images/thumb/6/67/Mk3_Monopropellant_Tank.png/190px-Mk3_Monopropellant_Tank.png)

There's a few places where yellow can be brought back. The RCS tanks I feel should definitely have variants with yellow stripes, the black checkers are *fine* but not great.

As for the yellow/black hazard stripes, they could see a come back to some elements on the LV-series engines and some of the exteriors of decouplers (along with blue and white stripes on stack separators), even if it's just as part variants. Obviously it should be more subtle than it was on the original models.

And finally, I think the golden insulation on the LV-909 "Terrier" should make a return as a variant. There was nothing unrealistic about it and it didn't need a foil tank to make sense like what we saw in Ven's. I mean, look at the insulation on the Falcon 9 upper stage. Could come in gold and silver to match the different insulations on the probe parts. I have occasionally used toroidal tanks clipped into the compact part variant, but it doesn't quite look the same as the conical slope. With ReStock, it could look more like it's covering bits of the engine, like on the Vacuum Merlin.

**Comment by ChrisAdderley** [comment]
I was going to close this with a snarky comment, but maybe let's explain.

This project was created to remove some of the specific things you want back. That's really the crux of why this will not happen. There has been a concerted effort to design every part category, not just in the sense of them being more realistic, but in the sense of tying common parts together with common design elements and languages. The initial stock designs do not have consistent, quality language.

Let's take yellow as a good example. What is yellow? Batteries, engines, xenon, some SRBs, monopropellant tanks, structural elements. Yes, this means that practically everything in stock at one point was yellow. Just because it was this way doesn't mean it was good.

We use the tools at our disposal to develop the languages we use, and one of them is colour.  One of our particular philosophies is the concept of base and highlight, and how the two should intertwine to clearly indicate the role and/or manufacturer of a part. Yellow is overloaded. Is it a highlight colour for SRBs? Is it for engines? Does it belong to a particular manufacturer? Who on earth knows? There's a similar story for a lot of features we looked at for all the part categories.

We're never going to bring back nasty design features for nostalgias sake - there would have to be a damn good reason to go and do this. There are a large number of nods in the mod to the original parts where we felt that including these elements helped create a consistent language of design. Lots of yellow definitely didn't make the cut.

**Comment by GregroxMun** [comment]
I greatly appreciate you not being snarky and actually explaining that.

**Comment by ChrisAdderley** [comment]
Strongly disagree with that last :).
