### ISSUE TITLE
Random Engines have shrouds on it

### ISSUE THREAD

**Issue by Starslinger909** [PorktoberRevolution/ReStocked#642]
This is only in flight, in editor it is not shown. No parts are beneath the engines. Happens with Vector Engine, Boar Engine and others will get as many pics as possible. Maybe related to #539 
![20190706202434_1](https://user-images.githubusercontent.com/36279460/60762390-c8d63f00-a02c-11e9-854e-bb3f75dc5c68.jpg) 
Vector engine on my booster where I discovered the issue.

**Comment by ChrisAdderley** [comment]
Can't reproduce this in my install, I suspect a mod conflict of some type because we'd have a lot of reports of this if it was consistent. Does this occur on all newly built craft? Is it every time a vessel is launched?

Can you also provide a comprehensive list of 
* Affected engines (and variants thereof if there are)
* Installed mods
* `output.txt` logfile

Thanks?

**Comment by ChrisAdderley** [comment]
It's been about a month with no response, so I'm closing this.
