### ISSUE TITLE
:FOR[ReStock] causing issues with other mods

### ISSUE THREAD

**Issue by DocRockwell** [PorktoberRevolution/ReStocked#806]
RealismOverhaul spawns variants of stock parts, but since the addition to :FOR[ReStock] in the restock configs, the ReStock changes get applied to the stock part after the new parts have been spawned, and the newly spawned parts are therefore broken.

What is the reason for adding :FOR[ReStock]? Doesn't it go without saying that ReStock configs are _for_ ReStock?

**Comment by ChrisAdderley** [comment]
Maybe in a semantic, for a person context, but no, this is not true for ModuleManager. MM considers all patches that don't declare a pass to be run in a legacy pass, which runs before all others. ModuleManager documentation could use some work. Basically it goes... bit of a simplification but:
1. FIRSTs
2. Legacy passes
3. Mod's BEFORE
4. Mod's FOR
5. Mod's AFTER

Running all a mod's content in the Legacy pass is bad for other mods targeting this mod, essentially.

**Comment by DocRockwell** [comment]
Could you recommend a solution? RealismOverhaul migrating to 1.8.1 now, and the new :FOR[ReStock] addition is causing issues with a lot of parts. I'm not sure if putting :AFTER[ReStock] in all the RO configs is the most practical solution either. 

Out of curiousity, what kind of adverse affects on other mods does having ReStock apply its patches in the legacy pass have?

**Comment by ChrisAdderley** [comment]
Nobody could target BEFORE, which was key for splitting off parts before restock touched them. 

If you pass me a particular RO patch file, I can take a look. However, the AFTER solution is probably where it's going to be.

**Comment by DocRockwell** [comment]
For example, parts based off solarPanels5, like solarPanels5HiTech (line 178) end up not working. The parts, while having ModuleManager entries, aren't getting the ReStock configs applied and don't appear in game, and crafts containing those parts can't be loaded.
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Electrical.cfg

Thanks for taking the time to consider this issue.

**Comment by ChrisAdderley** [comment]
Yeah, that's effectively the opposite problem than we just solved, haha.

Interestingly, this is also effectively the blacklist/whitelist problem. The cloning is happening pre-Restock, so it's referencing Squad assets that Restock stops from loading to save memory. There are two options here:

1. Include a whitelist file (see restock wiki) to ensure these parts have their assets available. This is the lowest-effort but has nonoptimal art results.
2. Define the patch as an AFTER restock thing. Though this would not seem completely awesome, to me this is MM behaving as i might expect and ensuring the load order is correctly alphabetical.

**Comment by RCrockford** [comment]
Hi, I have been looking at fixing this for a few weeks now, in RO.
I haven't come up with a good solution because just adding AFTER[ReStock] then breaks various other patches that are applied in passes like AFTER[RealismOverhaul] etc. Given RO has 6 of its own patching passes and relies on a few others (such as RealPlume) just moving things out to AFTER[ReStock] is a huge undertaking.

I can see three "solutions" such as they are:
1. Move all the RO passes such that they occur after ReStock - this is a large undertaking requiring updating multiple patching passes across around 500 cfgs. Needless to say this is not top of the list, though it is possible.
2. Move ReStock to an earlier pass. I tried a local change with this, moving ReStock to FOR[aReStock] and it worked nicely from RO's perspective. This may cause issues for other mods though.
3. Drop support for ReStock in RO. Also not a great solution.

**Comment by ChrisAdderley** [comment]
We are discussing options internally.

**Comment by ChrisAdderley** [comment]
Changed for `FOR[000_Restock]` with 1.1.2.
