### ISSUE TITLE
Deployable radiators leaving bits behind when broken

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#842]
The three deployable radiators leave behind the outer hinge when they get destroyed:
![screenshot776](https://user-images.githubusercontent.com/2611674/80281459-a4c82380-874e-11ea-9f09-fe570243870c.png)

![screenshot779](https://user-images.githubusercontent.com/2611674/80281517-05eff700-874f-11ea-9a62-de66e1516837.png)

I tried fixing in cfg by adding "%destroyOnBreakObjects =" with the transform names, but it didn't do anything. I guess ModuleDeployableRadiator doesn't inherit that part of ModuleDeployablePart for some reason?? Looks like it will need the hierarchy changed to fix

Stock:
![screenshot778](https://user-images.githubusercontent.com/2611674/80281483-d345fe80-874e-11ea-9856-b145e5f53ce8.png)

**Comment by ChrisAdderley** [comment]
Fixed in latest commit.

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/7cdb73d0a35fd310874cacd45c6f5f19cb99933e

On a side note, when testing I found this issue of all the debris flying away under 0g: https://www.youtube.com/watch?v=puVquYC_JFs Booted up Vanilla KSP to check and, yes, its a stock bug. There the best kind of issues to find. 😁
