### ISSUE TITLE
vertex out of position on 512k orange tank

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#843]
![Untitled](https://user-images.githubusercontent.com/2611674/80302126-86643580-87eb-11ea-980d-3952f1216fd0.png)
On the orange variant of the SIV-512K LFO tank, in currant master branch.

**Comment by ChrisAdderley** [comment]
Fixed in latest commit

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80320515-bcff7780-880e-11ea-946f-22747fb4574e.png)

Mesh fixed in https://github.com/PorktoberRevolution/ReStocked/commit/7cdb73d0a35fd310874cacd45c6f5f19cb99933e but I did spot that the thin orange ring at the top of the tank, just outside the silver end cap-ring, on one half of the model has a UV atlasing issue. See screenshot above. You can see where some other part of the texture map is being used for it.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/7cdb73d0a35fd310874cacd45c6f5f19cb99933e and https://github.com/PorktoberRevolution/ReStocked/commit/b4d446a9b80ded4ecbf5b16b8dfeb1d2a51d2d64
