### ISSUE TITLE
Normals not smoothed on small 5m raceway tips

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#847]
![screenshot790](https://user-images.githubusercontent.com/2611674/80304111-7d796100-87f7-11ea-93a0-90db21258f8f.png)
![screenshot789](https://user-images.githubusercontent.com/2611674/80304115-81a57e80-87f7-11ea-8db7-336b532a5ec0.png)

The 128 and 256 5m tanks' raceway caps have unsmoothed normals.

**Comment by Porkjet** [comment]
They are smooth, these edges are caused by triangulation making really sharp thin triangles on the cone-tapering, which act like vertical support loops causing semi-hard edges. Can be improved by adding support loops around the truncated cone, or possibly by condensing the tip loop into fewer vertices

**Comment by ChrisAdderley** [comment]
Mitigated in latest commit

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/7cdb73d0a35fd310874cacd45c6f5f19cb99933e
