### ISSUE TITLE
Compatibility Issue with Module manager supporting (EVE, Scatterer, and SVE) in 1.10.1

### ISSUE THREAD

**Issue by VelariYogesh** [PorktoberRevolution/ReStocked#908]
Kindly help me. Restock 1.2.0 (for KSP 1.10.1) and Visual enhancement modes (SVE with EVE and Scatterer) both works fine with KSP 1.10.1 when installed individually (in absent of other one). However on installing both together, they stop working, due to different supporting module manger. For visual enhancement, I am installing  the latest module manager (4.1.4) which is a folder while, Restock comes with a .dll file for that. Deleting one of the modulmanager is not solving the problem. Please help me with this. Looking forward to get the solution soon. Thank you very much. @nertea

**Comment by eberkain** [comment]
re-check the install instructions for module manager, I have only ever seen it placed in the root directory, not in a folder.

**Comment by Poodmund** [comment]
@VelariYogesh, please follow this guide on how to install Kerbal Space Program mods: https://forum.kerbalspaceprogram.com/index.php?/topic/182950-tutorial-how-to-install-mods-manually-ckan/

Additionally, ReStock is available for installation via CKAN if you wish to use that for a painless installation process.

I would suggest posting for support on the KSP Forum rather than on this GitHub repository as this is intended to highlight issues with the ReStock mod itself and not for installation support.
