### ISSUE TITLE
Restock reports unexpected directories related too fuel tanks

### ISSUE THREAD

**Issue by GrayTechGH** [PorktoberRevolution/ReStocked#935]
Restock reports installation issues.  It reports unexpected directories.  More specifically it reports fuelTankT100, fuelTankT200, fuelTankT400 and fuelTankT800.  I removed all mods but this error is still reported. I deleted all entries in the gamedata folder, reinstall the Squad and SquadExpansion folders,and then reinstall Restock and Restock+ through CKAN.  The error continues to be reported but does not otherwise effect the game.

![KSP Load screen](https://user-images.githubusercontent.com/43737130/105537255-a4e65700-5cbf-11eb-8329-f67344336920.png)

KSP 1.11
**List of mods installed:**
 - Restock 1.3.0
 - Restock+ 1.3.0

[KSPlog.zip](https://github.com/PorktoberRevolution/ReStocked/files/5858203/KSPlog.zip)

**Comment by ChrisAdderley** [comment]
First off, I'd suggest checking to see if you have those directories in your install.

**Comment by GrayTechGH** [comment]
I do have those folders.  I thought they may be from an older version so I deleted them and reinstalled from Steam using the 'verify integrity' option.  Steam recreated those files for 1.11 after I had deleted them.

**Comment by ChrisAdderley** [comment]
I don't get those in my install when doing that, so that's interesting. Are there files in there? Specifically configs.

**Comment by GrayTechGH** [comment]
fuelTankT100 contains fuelTankT100.cfg. It has no mu dds files.  The other folders are similar.  I
 did a complete reinstall for and the folder were recreated.  This is only for 1.11.  Those folders do not exist on my 1.10 install.

**Comment by ChrisAdderley** [comment]
I'll investigate to see if anyone on the team can reproduce this. It will indeed cause a problem if those configs are there, they really mess with ModuleManager part targeting.

**Comment by Poodmund** [comment]
Cannot reproduce. I deleted the entire GameData folder from my Vanilla Steam install, reverified the integrity of the game files which pulled down the 1.11.0 Squad and SquadExpansion folders, installed ReStock 1.3.0 and ReStock+ 1.3.0 and this issue is not present. Steam did not pull down the old Size 1 fuel tank folders or files.

I suspect this is user error(?) @GrayTechGH, I know that you said you had already done this but could we point you to: https://github.com/PorktoberRevolution/ReStocked/issues/581 and take note of the first issue listed, as that is what you're seeing. Both Nertea and I are not able to reproduce this issue in the same manner.

**Comment by GrayTechGH** [comment]
[Screenshots.zip](https://github.com/PorktoberRevolution/ReStocked/files/5862844/Screenshots.zip)

Thanks for letting me know it was an individual problem.  Here are some screenshots to show that I went through the usual procedure for a Steam reinstall, but if you want to skip this I think I found what was the issue.

I watch the install in detail and saw some saves show up first.  When I uninstalled again there were some left over folders and files.  I went into my KSP properties and disabled "Keep game saves...".   When I reinstalled again these files were not created.
