### ISSUE TITLE
Improvement : CLS Compatibility

### ISSUE THREAD

**Issue by mwerle** [PorktoberRevolution/ReStocked#991]
Restock changes the visuals of several stock parts to include additional hatches compared to the stock visuals.

A user has supplied a patch to CLS for the affected ReStock parts, however, there's an argument to be made that this patch would be better shipped with ReStock.  This would allow ReStock authors to keep the CLS patch up-to-date with any future artwork changes.

Thoughts?

The patch: https://github.com/codepoetpbowden/ConnectedLivingSpace/pull/118/commits/cc9cf304f06617067fe17f1d63412174bf3c2eb4

The original issue: https://github.com/codepoetpbowden/ConnectedLivingSpace/issues/117

**Comment by Poodmund** [comment]
There is unlikely to ever be any future artwork changes to the mod and patches already exist within CLS to work with ReStock (https://github.com/codepoetpbowden/ConnectedLivingSpace/pull/113) so I think it would be better for it to be handled within CLS as there's likely going to be more active development and more frequent releases to handle these issues.

As an addendum, ReStock also causes issues with CLS due to the part variant system, see https://github.com/PorktoberRevolution/ReStocked/issues/959

**Comment by mwerle** [comment]
Thanks for your reply and feedback. So we'll continue to support ReStock (and ReStock+) directly within CLS.
